// The object store behind lib/server.ts's `bucket()`, in the exact shape this
// app already calls on Cloudflare R2:
//
//   await bucket().get(key)    -> { body, httpMetadata: { contentType } } | null
//   await bucket().put(key, bytes, { httpMetadata: { contentType } })
//   await bucket().delete(key)
//
// Two drivers share that surface:
//   - Netlify Blobs, for the deployed site;
//   - a plain directory (default `.data/blobs`), so the shop runs on a laptop
//     with no Netlify account.
//
// `.head()` is not called by the app today. It is here because both drivers can
// answer "does this key exist, and with which Content-Type" identically, and
// scripts/verify-blob-store.mjs uses it. `.list()` is deliberately absent: a
// missing method is a loud TypeError, not a silently wrong answer.
import { mkdir, readFile, rm, stat, writeFile } from "node:fs/promises";
import { dirname, resolve, sep } from "node:path";
import { getStore, type Store } from "@netlify/blobs";

export interface BlobHttpMetadata {
  /** R2's `httpMetadata.contentType`: what /api/media serves the file back as. */
  contentType?: string;
}

export interface StoredBlob {
  /** Handed straight to `new Response(...)`, exactly as R2Object.body was. */
  body: ReadableStream<Uint8Array> | Uint8Array;
  httpMetadata?: BlobHttpMetadata;
}

export interface BlobPutOptions {
  httpMetadata?: BlobHttpMetadata;
}

export interface BlobStore {
  get(key: string): Promise<StoredBlob | null>;
  put(
    key: string,
    bytes: ArrayBuffer | Uint8Array,
    options?: BlobPutOptions,
  ): Promise<void>;
  delete(key: string): Promise<void>;
  /** Content type only: Netlify's HEAD gives no size, so neither driver claims one. */
  head(key: string): Promise<BlobHttpMetadata | null>;
}

export const DEFAULT_BLOB_STORE_NAME = "pawpal-media";
export const DEFAULT_LOCAL_BLOB_DIR = ".data/blobs";

/**
 * GET /api/media/* takes its key straight from the URL, so a key is untrusted
 * input. Every segment must look like the keys the app writes
 * (`products/<uuid>`, `slips/<orderId>/<uuid>`): no empty segment, no `.`, no
 * `..`, no percent escapes, no backslash, nothing that could walk out of the
 * local blob directory or forge extra path segments in a Netlify URL.
 */
const KEY_SEGMENT = /^[A-Za-z0-9][A-Za-z0-9._-]*$/;

export function isSafeKey(key: string): boolean {
  if (typeof key !== "string" || !key || key.length > 512) return false;
  return key.split("/").every((segment) => KEY_SEGMENT.test(segment));
}

/** Keys we write are generated by the app, so a bad one is a bug, not a request. */
function assertWritableKey(key: string): void {
  if (!isSafeKey(key)) throw new TypeError(`Unsupported blob key: ${key}`);
}

function toBytes(bytes: ArrayBuffer | Uint8Array): Uint8Array {
  return bytes instanceof Uint8Array ? bytes : new Uint8Array(bytes);
}

function toArrayBuffer(bytes: ArrayBuffer | Uint8Array): ArrayBuffer {
  if (!(bytes instanceof Uint8Array)) return bytes;
  return new Uint8Array(bytes).buffer as ArrayBuffer;
}

function contentTypeOf(metadata: unknown): string | undefined {
  if (!metadata || typeof metadata !== "object") return undefined;
  const value = (metadata as { contentType?: unknown }).contentType;
  return typeof value === "string" && value ? value : undefined;
}

function isMissing(error: unknown): boolean {
  const code = (error as NodeJS.ErrnoException | null)?.code;
  return code === "ENOENT" || code === "ENOTDIR" || code === "EISDIR";
}

// --- Netlify Blobs ---------------------------------------------------------

interface NetlifyBlobsContext {
  siteID?: string;
  token?: string;
  edgeURL?: string;
  uncachedEdgeURL?: string;
}

/**
 * The same base64 JSON blob `@netlify/blobs` reads. We decode it ourselves only
 * to answer one question: can this runtime serve a strongly consistent read?
 */
export function netlifyBlobsContext(): NetlifyBlobsContext | null {
  const raw =
    (globalThis as { netlifyBlobsContext?: unknown }).netlifyBlobsContext ??
    process.env.NETLIFY_BLOBS_CONTEXT;
  if (typeof raw !== "string" || !raw) return null;
  try {
    const parsed: unknown = JSON.parse(
      Buffer.from(raw, "base64").toString("utf8"),
    );
    return parsed && typeof parsed === "object"
      ? (parsed as NetlifyBlobsContext)
      : null;
  } catch {
    return null;
  }
}

/** True when a Netlify runtime is present, whether or not blobs are configured. */
export function onNetlify(): boolean {
  return (
    process.env.NETLIFY === "true" ||
    typeof process.env.NETLIFY_BLOBS_CONTEXT === "string" ||
    typeof (globalThis as { netlifyBlobsContext?: unknown })
      .netlifyBlobsContext === "string"
  );
}

export function createNetlifyBlobStore(
  name: string = DEFAULT_BLOB_STORE_NAME,
): BlobStore {
  // Strong consistency is not a nicety here. POST /api/orders/:id/slip writes
  // the slip, immediately flips the order to "reviewing", and the customer's
  // next paint fetches /api/media/slips/... . An eventually consistent read
  // would show a "lost slip" that is in fact stored.
  //
  // The client refuses strong consistency when the environment gives it an
  // edge URL but no uncached edge URL (older runtimes, connectLambda), so in
  // that case we address the Netlify API directly by passing siteID/token,
  // which bypasses the edge reader and is strongly consistent by construction.
  const context = netlifyBlobsContext();
  const siteID = context?.siteID;
  const token = context?.token;
  const edgeOnly = Boolean(
    context?.edgeURL && !context?.uncachedEdgeURL && siteID && token,
  );
  if (edgeOnly)
    console.warn(
      "PAWPAL: this Netlify runtime exposes no uncached edge URL; reading blobs through the API so slips stay strongly consistent.",
    );
  const store: Store =
    edgeOnly && siteID && token
      ? getStore({ name, consistency: "strong", siteID, token })
      : getStore({ name, consistency: "strong" });

  return {
    async get(key) {
      if (!isSafeKey(key)) return null;
      const found = await store.getWithMetadata(key, { type: "stream" });
      if (!found || !found.data) return null;
      return {
        body: found.data as ReadableStream<Uint8Array>,
        httpMetadata: { contentType: contentTypeOf(found.metadata) },
      };
    },
    async put(key, bytes, options) {
      assertWritableKey(key);
      const contentType = options?.httpMetadata?.contentType;
      await store.set(key, toArrayBuffer(bytes), {
        metadata: contentType ? { contentType } : {},
      });
    },
    async delete(key) {
      if (!isSafeKey(key)) return;
      await store.delete(key);
    },
    async head(key) {
      if (!isSafeKey(key)) return null;
      const found = await store.getMetadata(key);
      if (!found) return null;
      return { contentType: contentTypeOf(found.metadata) };
    },
  };
}

// --- Local filesystem ------------------------------------------------------

/**
 * Bytes live in `<directory>/objects/<key>`, content types in
 * `<directory>/meta/<key>.json`. Two trees rather than a sidecar beside the
 * bytes, so no request for `<key>.json` can ever read another key's metadata:
 * /api/media/products/* is public and takes its key from the URL.
 */
export function createLocalBlobStore(
  directory: string = DEFAULT_LOCAL_BLOB_DIR,
): BlobStore {
  const root = resolve(directory);
  const within = (path: string) => path.startsWith(root + sep);
  const objectPath = (key: string) => resolve(root, "objects", key);
  const metaPath = (key: string) => resolve(root, "meta", `${key}.json`);

  async function readContentType(key: string): Promise<string | undefined> {
    const path = metaPath(key);
    if (!within(path)) return undefined;
    try {
      return contentTypeOf(JSON.parse(await readFile(path, "utf8")));
    } catch {
      return undefined;
    }
  }

  return {
    async get(key) {
      if (!isSafeKey(key)) return null;
      const path = objectPath(key);
      if (!within(path)) return null;
      let data: Buffer;
      try {
        data = await readFile(path);
      } catch (error) {
        if (isMissing(error)) return null;
        throw error;
      }
      return {
        body: new Uint8Array(data),
        httpMetadata: { contentType: await readContentType(key) },
      };
    },
    async put(key, bytes, options) {
      assertWritableKey(key);
      const object = objectPath(key);
      const meta = metaPath(key);
      if (!within(object) || !within(meta))
        throw new TypeError(`Unsupported blob key: ${key}`);
      // Metadata first: a reader must never find bytes without their type.
      await mkdir(dirname(meta), { recursive: true });
      await writeFile(
        meta,
        JSON.stringify({
          contentType: options?.httpMetadata?.contentType ?? null,
        }),
      );
      await mkdir(dirname(object), { recursive: true });
      await writeFile(object, toBytes(bytes));
    },
    async delete(key) {
      if (!isSafeKey(key)) return;
      const object = objectPath(key);
      const meta = metaPath(key);
      if (!within(object) || !within(meta)) return;
      await rm(object, { force: true });
      await rm(meta, { force: true });
    },
    async head(key) {
      if (!isSafeKey(key)) return null;
      const path = objectPath(key);
      if (!within(path)) return null;
      try {
        await stat(path);
      } catch (error) {
        if (isMissing(error)) return null;
        throw error;
      }
      return { contentType: await readContentType(key) };
    },
  };
}
